title: My blogs
description: 学习过程的一点思绪
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-feed

header_pages:
  - categories.md